# Generated by Django 4.2.5 on 2023-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='n_order',
            field=models.TextField(null=True),
        ),
    ]
